### ISSUE TITLE
preserve the HTML in "words" count mode?

### ISSUE THREAD

**Issue by rodrigoAbril** [vaakash/jquery-collapser#1]
is there some way to preserve the HTML in "words" count mode?

**Comment by vaakash** [comment]
Hi rodrigoAbril, in collapsed mode the text is stripped off to make counting of words/characters and placing breakpoints accurate and simple. If HTML is preserved there will be issues if images are present ! If there is a CSS issue in collapsed state, you can assign some class in collapsed mode and style it as required. Thanks !
